### PR TITLE
Use fixed 0.13.x handlebars loader

### PR DESCRIPTION
**Pull request by MCGallaspy**
We'll see if this works.

### CODE REVIEW

**Comment by 66eli77** [comment]
tested on Mac and doesn't create issues. @MCGallaspy does it works on Windows? if so, I'm going to merge it

**Comment by MCGallaspy** [comment]
Yes, please merge

**Comment by MCGallaspy** [comment]
Though is WCH using macs?

**Comment by 66eli77** [comment]
No, they don't. Merging

**Pull request merged**
